CREATE DATABASE IF NOT EXISTS HOSPITAL;
USE HOSPITAL;

CREATE TABLE ESPECIALIDADE(
    ID_ESPECIALIDADE INT PRIMARY KEY,
    ESPECIALIDADE VARCHAR(255)
);


CREATE TABLE CONVENIO(
    ID_CONVENIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    CNPJ BIGINT
);

CREATE TABLE MEDICO(
    CRM_ID INT PRIMARY KEY,
    TELEFONE VARCHAR(24),
    EMAIL VARCHAR(255),
    ID_ESPECIALIDADE INT,
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);

CREATE TABLE PACIENTE(
    CPF_PACIENTE BIGINT PRIMARY KEY,
    NOME VARCHAR(255),
    ENDERECO VARCHAR(255),
    TELEFONE BIGINT,
    DATA_NASCIMENTO DATE,
    ID_CONVENIO INT,
    FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO(ID_CONVENIO)
);

CREATE TABLE CONSULTA(
    ID_CONSULTA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_HORA DATETIME,
    CRM_ID INT,
    ID_CONVENIO INT,
    ID_ESPECIALIDADE INT,
    CPF_PACIENTE BIGINT,
    FOREIGN KEY (CRM_ID) REFERENCES MEDICO(CRM_ID),
    FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO(ID_CONVENIO),
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF_PACIENTE)
);

CREATE TABLE RECEITA(
    ID_RECEITA INT PRIMARY KEY AUTO_INCREMENT,
    MEDICAMENTOS VARCHAR(255),
    QUANTIDADE INT,
    INSTRUCOES TEXT,
    ID_CONSULTA INT,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
);

CREATE TABLE QUARTO(
    ID_QUARTO INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_QUARTO INT,
    TIPO_QUARTO INT,
    CPF_PACIENTE BIGINT,
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF_PACIENTE)
);

CREATE TABLE INTERNACAO(
    ID_INTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_ENTRADA DATETIME,
    DATA_SAIDA DATETIME,
    ID_QUARTO INT,
    CPF_PACIENTE BIGINT, 
    FOREIGN KEY (ID_QUARTO) REFERENCES QUARTO(ID_QUARTO),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF_PACIENTE)
);

CREATE TABLE DOCUMENTO(
    ID_DOCUMENTO INT PRIMARY KEY AUTO_INCREMENT,
    CAMINHO_DOCUMENTO VARCHAR(255),
    CPF_PACIENTE BIGINT,
    FOREIGN KEY (CPF_PACIENTE) REFERENCES PACIENTE(CPF_PACIENTE)
);

CREATE TABLE ENFERMEIRO(
    ID_COREM INT PRIMARY KEY,
    ID_QUARTO INT,
    FOREIGN KEY (ID_QUARTO) REFERENCES QUARTO(ID_QUARTO)
);
ALTER TABLE MEDICO
ADD COLUMN NOME VARCHAR(255);
